### ISSUE TITLE
Demo URL not working

### ISSUE THREAD

**Issue by HendrikRunte** [PulexIrritans/Heelhook-Capstone#53]
Readme.md points to a non-existant vercel URL: https://heelhook-capstone.vercel.app/
Possible fix: https://heelhook.vercel.app

<3

**Comment by PulexIrritans** [comment]
Hendrik, thank you so much for pointing this out. I fixed it immediately. You can check again if you want. 
<3

**Comment by HendrikRunte** [comment]
Pleasure! <3
